CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255)
);

CREATE TABLE visit (
 id SERIAL primary key,
 date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ALTER TABLE visite ADD COLUMN user_agent VARCHAR(255);
